-- =============================================
-- Build Manifests - Project Builder configurations
-- Stores manifests generated by the web Project Builder
-- that users download and run in pyRevit locally
-- =============================================

CREATE TABLE IF NOT EXISTS build_manifests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES projects(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    project_type TEXT NOT NULL CHECK (project_type IN ('residential', 'commercial', 'industrial')),
    manifest JSONB NOT NULL DEFAULT '{}',
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for fast project-based lookups
CREATE INDEX IF NOT EXISTS idx_build_manifests_project_id ON build_manifests(project_id);
CREATE INDEX IF NOT EXISTS idx_build_manifests_created_at ON build_manifests(created_at DESC);

-- RLS
ALTER TABLE build_manifests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "build_manifests_select" ON build_manifests
    FOR SELECT USING (true);

CREATE POLICY "build_manifests_insert" ON build_manifests
    FOR INSERT WITH CHECK (true);

CREATE POLICY "build_manifests_update" ON build_manifests
    FOR UPDATE USING (true);

CREATE POLICY "build_manifests_delete" ON build_manifests
    FOR DELETE USING (true);
