-- =============================================================================
-- Calendar — Phase 3 schema (ICS feed tokens + reminder dispatch log)
-- =============================================================================
-- Adds two supporting tables for the Phase 3 polish features:
--
--   1. user_calendar_tokens     — opaque tokens for /calendar/feed.ics subscriptions
--                                  (one row per (user, label) so a user can revoke
--                                  one device without invalidating the others)
--   2. calendar_reminder_log    — idempotency log for the cron dispatcher; one row
--                                  per (event_id, occurrence_at) that has been
--                                  notified, so a re-run never fires twice
--
-- Idempotent. Run on staging first, then prod (Supabase SQL editor).
-- Path: C:\Users\germa\Desktop\NGM_API\sql\calendar_phase3_ics_and_reminders.sql
-- =============================================================================


-- =============================================================================
-- 1. user_calendar_tokens — ICS feed subscription tokens
-- =============================================================================
-- The token itself is treated as a secret (URL-safe random, generated by the
-- backend). Lookups are by token so anyone with the URL can fetch the feed —
-- this is intentional for ICS subscribers (Apple Calendar, Outlook, Google).
-- Revoke by deleting the row.

CREATE TABLE IF NOT EXISTS user_calendar_tokens (
    token        text PRIMARY KEY,                 -- url-safe random, set by API
    user_id      uuid NOT NULL,                    -- soft ref -> users.user_id
    label        text NOT NULL DEFAULT 'default',  -- human label (e.g. "Phone", "Outlook")
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz
);

-- "List my tokens" + de-dupe label per user.
CREATE UNIQUE INDEX IF NOT EXISTS uq_uct_user_label
    ON user_calendar_tokens (user_id, lower(label));
CREATE INDEX IF NOT EXISTS idx_uct_user
    ON user_calendar_tokens (user_id);


-- =============================================================================
-- 2. calendar_reminder_log — cron dispatch idempotency
-- =============================================================================
-- One row per (event_id, occurrence_at) that has been notified. The dispatcher
-- writes a row BEFORE sending notifications and skips events that already have
-- one — so reruns / overlapping cron jobs / Render dyno restarts can't double-
-- fire reminders. Cleanup by TTL (rows older than 60 days).

CREATE TABLE IF NOT EXISTS calendar_reminder_log (
    event_id        uuid NOT NULL REFERENCES calendar_events(event_id) ON DELETE CASCADE,
    occurrence_at   timestamptz NOT NULL,
    dispatched_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id, occurrence_at)
);

CREATE INDEX IF NOT EXISTS idx_crl_dispatched
    ON calendar_reminder_log (dispatched_at);


-- =============================================================================
-- RLS — service_role full access (backend API); no public select.
-- (Token rows must never be readable from the anon/authenticated role; the API
-- mediates all access using the service_role key.)
-- =============================================================================
ALTER TABLE user_calendar_tokens    ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_reminder_log   ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies
                   WHERE tablename='user_calendar_tokens' AND policyname='uct_service_all') THEN
        CREATE POLICY uct_service_all ON user_calendar_tokens
            FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies
                   WHERE tablename='calendar_reminder_log' AND policyname='crl_service_all') THEN
        CREATE POLICY crl_service_all ON calendar_reminder_log
            FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
END $$;


-- =============================================================================
-- VERIFICATION
-- =============================================================================
-- select count(*) from user_calendar_tokens;
-- select count(*) from calendar_reminder_log;
-- select column_name, data_type from information_schema.columns
--   where table_name='user_calendar_tokens' order by ordinal_position;
